apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/prometheus/metrics"
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.route-prefix=/prometheus"
          - "--web.external-url=${INGRESS_CONTROLLER_PROT}://${INGRESS_CONTROLLER_ADDR}/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: prometheus
          mountPath: /prometheus
        resources:
          requests:
            cpu: 120m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 500Mi
      volumes:
      - name: config
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: prometheus
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/prometheus/metrics"
spec:
  selector:
    app: prometheus
  ports:
  - port: 80
    targetPort: 9090
