apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
  labels:
    app: node-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: node-redis
          image: faioa/crv:tme6-node-redis-image
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: "3000"
          - name: REDIS_URL
            value: "redis://redis.default.svc.cluster.local:6379"
          - name: REDIS_REPLICAS_URL
            value: "redis://redis-replica.default.svc.cluster.local:6379"
          resources:
            requests:
              cpu: 75m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: node-redis
spec:
  selector:
    app: node-redis
  ports:
  - port: 80
    targetPort: 3000
