apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = "${INGRESS_CONTROLLER_ADDR}"
    root_url = "${INGRESS_CONTROLLER_PROT}://${INGRESS_CONTROLLER_ADDR}/grafana/"
    serve_from_sub_path = true
    enforce_domain = false

    [security]
    cookie_secure = false
    cookie_samesite = lax

    [log]
    mode = console
    level = info

    [auth]
    disable_login_form = false

    [auth.anonymous]
    enabled = false
    org_name = Main Org.
    org_role = Viewer
