{
 "title": "SRE",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods' State",
   "type": "table",
   "description": "This panel describes the Pods' states in real time",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(kube_pod_status_phase{pod=~\"(redis|node-redis|ingress-nginx).*\"}[10s])",
     "legendFormat": "{{pod}} : {{phase}}"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "description": "This panel describes the number of Pods running simultaneously.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_app=\"redis\"})",
     "legendFormat": "Redis"
    },
    {
     "expr": "sum(kube_pod_labels{label_app=\"redis-replica\"})",
     "legendFormat": "Redis-Replica"
    },
    {
     "expr": "sum(kube_pod_labels{label_app=\"node-redis\"})",
     "legendFormat": "Node-Redis"
    },
    {
     "expr": "sum(kube_pod_labels{label_app=\"redis-react\"})",
     "legendFormat": "Redis-React"
    },
    {
     "expr": "sum(kube_pod_labels{pod=~\"ingress-nginx-controller.*\"})",
     "legendFormat": "Ingress-Controller"
    }
   ]
  },
  {
   "title": "Max CPU Usage (cores)",
   "type": "stat",
   "description": "This panel describes the maximum CPU usage of each Pod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"node-redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"ingress-nginx-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Usage",
   "type": "stat",
   "description": "This panel describes the maximum memory usage of each Pod.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"node-redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"ingress-nginx-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "description": "This panel describes the CPU usage of each Pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"redis.*\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"node-redis.*\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"ingress-nginx-controller.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "description": "This panel describes the memory usage of our Pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"node-redis.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"ingress-nginx-controller.*\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "This panel describes the CPU usage percentage of each Service that uses HPA, grouped by Pods.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"redis.*\"}[1m])) / sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"redis.*\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"node-redis.*\"}[1m])) / sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"node-redis.*\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"ingress-nginx-controller.*\"}[1m])) / sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"ingress-nginx-controller.*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "description": "This panel describes the CPU usage percentage of each Pods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"redis.*\"}) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"redis.*\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"node-redis.*\"}) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"node-redis.*\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"ingress-nginx-controller.*\"}) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"ingress-nginx-controller.*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Clients Connected (Redis)",
   "type": "timeseries",
   "description": "This panel describes how many clients are connected to a Redis instance (Redis or Redis-Replica)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{app=~\"redis.*\", app!=\"redis-react\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Requests per Second",
   "type": "timeseries",
   "description": "This panel describes the number of requests per second for each endpoint that was already queried.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route, method) (\n  idelta(http_requests_total{app=\"node-redis\"}[15m])\n  or\n  http_requests_total{app=\"node-redis\"} > 0\n)",
     "legendFormat": "{{method}} : {{route}}"
    }
   ]
  },
  {
   "title": "Average Latency (Redis)",
   "type": "timeseries",
   "description": "This panel describes the average time clients need to wait until their requests are completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(cmd) (redis_latency_percentiles_usec)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Average Latency (HTTP)",
   "type": "timeseries",
   "description": "This panel describes the average time clients need to wait until their requests are completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method, route) (\n  (\n    rate(http_request_duration_seconds_sum{app=\"node-redis\"}[2s])\n    /\n    rate(http_request_duration_seconds_count{app=\"node-redis\"}[2s])\n  )\n  or\n  (\n    http_request_duration_seconds_sum{app=\"node-redis\"}\n    /\n    http_request_duration_seconds_count{app=\"node-redis\"}\n  )\n)",
     "legendFormat": "{{method}} : {{route}}"
    }
   ]
  },
  {
   "title": "Services Errors (%)",
   "type": "timeseries",
   "description": "This panel describes the percentage of errors when querying the services",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by(route, method) (\n    idelta(http_requests_total{status=~\"[45]XX\", app=\"node-redis\"}[15m])\n    or\n    http_requests_total{status=~\"[45]XX\", app=\"node-redis\"}\n    or\n    0 * http_requests_total{app=\"node-redis\"}\n  )\n  /\n  sum by(route, method) (\n    idelta(http_requests_total{app=\"node-redis\"}[15m])\n    or\n    http_requests_total{app=\"node-redis\"} > 0\n  )\n) * 100",
     "legendFormat": "{{method}} : {{route}} {{status}}"
    }
   ]
  }
 ]
}