apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-deployment
  labels:
    app: node-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          image: faioa/crv:tme6-node-redis-image
          ports:
          - containerPort: 3000
          env:
          - name: REDIS_URL
            value: "redis://redis.default.svc.cluster.local:6379"
          - name: REDIS_REPLICAS
            value: "redis://redis.default.svc.cluster.local:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: node-redis
spec:
  type: LoadBalancer
  selector:
    app: node-redis
  ports:
  - port: 80
    targetPort: 3000
