apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-react
  labels:
    app: redis-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-react
  template:
    metadata:
      labels:
        app: redis-react
    spec:
      containers:
        - name: redis-react
          image: faioa/crv:tme6-redis-react-image
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: "API_URL"
            value: "${INGRESS_CONTROLLER_PROT}://${INGRESS_CONTROLLER_ADDR}/node-redis"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 40m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-react
spec:
  selector:
    app: redis-react
  ports:
  - port: 80
    targetPort: 8080
